#!/bin/sh

PKG=`pwd | xargs basename`
VER=1.0
EMAIL=$PKG-$VER-maintainer@gnu.org
ME=bootstrap

TEMP=`getopt -o fh --long help,force -- "$@"`
if [ $? != 0 ] ; then echo "bootstrap: terminating" >&2 ; exit 1 ; fi
eval set -- "$TEMP"

while true; do
    case "$1" in
	-f|--force) FORCE=1; shift;;
	-h|--help) HELP=1; shift;;
	--) shift; break;;
    esac
done

[ -n "$HELP" ] && echo "usage: $ME [-f|--force]" && exit 0

for f in Makefile.am NEWS README AUTHORS ChangeLog; do 
    [ ! -e $f ] && echo "$ME: installing \`$f'" && touch $f
done

if [ -n "$FORCE" ] || [ ! -e configure.in ]; then
    echo "$ME: running autoscan" && autoscan 
    [ -e configure.scan ] && echo "$ME: installing \`configure.in'" \
	&& perl -npe"s/^AC_INIT\((.*?)\)$/AC_INIT($PKG,$VER,$EMAIL)\nAM_INIT_AUTOMAKE($PKG,$VER)/" \
	configure.scan > configure.in
fi

[ -e configure.in ] \
    && echo "$ME: running aclocal" && aclocal \
    && echo "$ME: running autoheader" && autoheader \
    && echo "$ME: running automake --gnu --add-missing --copy" && automake --gnu --add-missing --copy\
    && echo "$ME: running autoconf" && autoconf
